import {Campaign} from "./model";

export const HEALTHY_CAMPAIGN: Campaign = {
    assetPath: "healthy",
    assetPaths: {
        background: "{background}_{size}.png",
        header: "{background}_header_{language}.png",
        defaultPicture: "{background}_defaultpicture.png",
        antiDefaultPicture: "{background}_frame.png",
    },
    languages: ["English", "Spanish"],
    backgrounds: [
        {name: "Accountability", color: "#fdedd6"},
        {name: "Boundaries", color: "#ad89e1"},
        {name: "Consent", color: "#fdedd6"},
        {name: "Equality", color: "#5a7424"},
        {name: "Healthy Conflict", color: "#5a7424"},
        {name: "Honesty", color: "#42347b"},
        {name: "Independence", color: "#fde4d6"},
        {name: "Joy", color: "#fff9c7"},
        {name: "Respect", color: "#42347b"},
        {name: "Trust", color: "#2c5996"},
    ],
    sizes: [
        {
            name: "8.5x11",
            label: "8.5x11",
            width: 1545,
            height: 2000,
            header: {
                x: 0,
                y: 96,
                width: 1545,
                height: 1904,
                horizontalAlignment: 'center',
                verticalAlignment: 'top',
            },
            defaultPicture: {
                x: 34,
                y: 462,
                width: 1477,
                height: 1372,
                horizontalAlignment: 'center',
                verticalAlignment: 'bottom',
                scaleStrategy: 'fill',
            },
            antiDefaultPicture: {
                x: 169,
                y: 512,
                width: 1206,
                height: 1339,
                horizontalAlignment: 'center',
                verticalAlignment: 'center',
            },
            picture: {
                x: 273,
                y: 611,
                width: 989,
                height: 1141,
                enforceAspectRatio: true,
            },
            logo: {
                x: 1323,
                y: 1646,
                width: 188,
                height: 188,
                horizontalAlignment: 'right',
            },
            website: {
                x: 1545,
                y: 0,
                horizontalAlignment: 'right',
                verticalAlignment: 'top',
                includeBackgroundFill: true,
            },
            programInfo: {
                x: 772,
                y: 1907,
                horizontalAlignment: 'center',
                verticalAlignment: 'center',
                lineDistribution: 'center',
            },
        },
        {
            name: "11x17",
            label: "11x17",
            width: 1294,
            height: 2000,
            header: {
                x: 0,
                y: 96,
                width: 1294,
                height: 1904,
                horizontalAlignment: 'center',
                verticalAlignment: 'top',
            },
            defaultPicture: {
                x: 32,
                y: 562,
                width: 1230,
                height: 1274,
                horizontalAlignment: 'center',
                verticalAlignment: 'bottom',
                scaleStrategy: 'fill',
            },
            antiDefaultPicture: {
                x: 142,
                y: 601,
                width: 1010,
                height: 1121,
                horizontalAlignment: 'center',
                verticalAlignment: 'center',
            },
            picture: {
                x: 229,
                y: 684,
                width: 828,
                height: 956,
                enforceAspectRatio: true,
            },
            logo: {
                x: 1075,
                y: 1647,
                width: 187,
                height: 187,
                horizontalAlignment: 'right',
            },
            website: {
                x: 1294,
                y: 0,
                horizontalAlignment: 'right',
                verticalAlignment: 'top',
                includeBackgroundFill: true,
            },
            programInfo: {
                x: 647,
                y: 1907,
                horizontalAlignment: 'center',
                verticalAlignment: 'center',
                lineDistribution: 'center',
            },
        },
        {
            name: "12x18",
            label: "12x18",
            width: 1333,
            height: 2000,
            header: {
                x: 0,
                y: 96,
                width: 1333,
                height: 1904,
                horizontalAlignment: 'center',
                verticalAlignment: 'top',
            },
            defaultPicture: {
                x: 32,
                y: 562,
                width: 1269,
                height: 1297,
                horizontalAlignment: 'center',
                verticalAlignment: 'bottom',
                scaleStrategy: 'fill',
            },
            antiDefaultPicture: {
                x: 146,
                y: 551,
                width: 1041,
                height: 1155,
                horizontalAlignment: 'center',
                verticalAlignment: 'center',
            },
            picture: {
                x: 236,
                y: 636,
                width: 853,
                height: 984,
                enforceAspectRatio: true,
            },
            logo: {
                x: 1139,
                y: 1697,
                width: 162,
                height: 162,
                horizontalAlignment: 'right',
            },
            website: {
                x: 1333,
                y: 0,
                horizontalAlignment: 'right',
                verticalAlignment: 'top',
                includeBackgroundFill: true,
            },
            programInfo: {
                x: 666,
                y: 1919,
                horizontalAlignment: 'center',
                verticalAlignment: 'center',
                lineDistribution: 'center',
            },
        },
    ]
}
