import {Campaign} from "./model";

export const SURVIVOR_CAMPAIGN: Campaign = {
    assetPath: "images",
    assetPaths: {
        background: "{background}_{size}.png",
        header: "header_{language}.png",
        defaultPicture: "{background}_defaultpicture_{language}.png",
        antiDefaultPicture: "{background}_antidefaultpicture_{language}.png",
    },
    languages: ["English", "Spanish"],
    suggestTransparentPictures: true,
    backgrounds: [
        {name: "Boundaries", color: "#ffbd59", fontColor: "#000000"},
        {name: "Experience", color: "#9d7bd9", fontColor: "#000000"},
        {name: "Gentle", color: "#ccb4ae", fontColor: "#000000"},
        {name: "Healing", color: "#64cca3", fontColor: "#000000"},
        {name: "Not Alone", color: "#81e7a2", fontColor: "#000000"},
        {name: "Progress", color: "#f7e367", fontColor: "#000000"},
        {name: "Resilient", color: "#b1a1fa", fontColor: "#000000"},
        {name: "Space", color: "#f36e80", fontColor: "#000000"},
        {name: "Support", color: "#5485e1", fontColor: "#000000"},
        {name: "Valid", color: "#7acbef", fontColor: "#000000"},
        {name: "Voice", color: "#4ea23e", fontColor: "#000000"},
        {name: "Worthy", color: "#f09333", fontColor: "#000000"},
    ],
    sizes: [
        {
            name: "11x14",
            label: "11x14",
            width: 1571,
            height: 2000,
            header: {
                x: 0,
                y: 214,
                width: 1571,
                height: 1786,
                horizontalAlignment: 'center',
                verticalAlignment: 'top',
            },
            defaultPicture: {
                x: 0,
                y: 380,
                width: 1571,
                height: 1445,
                horizontalAlignment: 'center',
                verticalAlignment: 'bottom',
            },
            antiDefaultPicture: {
                x: 0,
                y: 355,
                width: 1571,
                height: 1645,
                horizontalAlignment: 'center',
                verticalAlignment: 'top',
            },
            picture: {
                x: 0,
                y: 590,
                width: 1571,
                height: 1235,
                horizontalAlignment: 'center',
                verticalAlignment: 'bottom',
            },
            logo: {
                x: 1396,
                y: 1825,
                width: 175,
                height: 175,
                horizontalAlignment: 'right',
            },
            website: {
                x: 1571,
                y: 0,
                horizontalAlignment: 'right',
                lineDistribution: 'down',
                includeBackgroundFill: true,
            },
            programInfo: {
                x: 698,
                y: 1902,
                horizontalAlignment: 'center',
                lineDistribution: 'center',
            },
            defaultPictureWebsiteExtraText: {
                fontSize: 40,
                text: {
                    "english": "Campaign by Recognize Violence, Change Culture (RVCC)",
                    "spanish": "Campaña de Recognize Violence, Change Culture (RVCC)",
                },
            },
        },
        {
            name: "square",
            label: "Social media post",
            width: 1080,
            height: 1080,
            header: {
                x: 0,
                y: 109,
                width: 1080,
                height: 971,
                horizontalAlignment: 'center',
                verticalAlignment: 'top',
            },
            defaultPicture: {
                x: 0,
                y: 263,
                width: 1080,
                height: 715,
                horizontalAlignment: 'center',
                verticalAlignment: 'bottom',
            },
            antiDefaultPicture: {
                x: 0,
                y: 250,
                width: 1080,
                height: 830,
                horizontalAlignment: 'center',
                verticalAlignment: 'top',
            },
            picture: {
                x: 0,
                y: 485,
                width: 1080,
                height: 493,
                horizontalAlignment: 'center',
                verticalAlignment: 'bottom',
            },
            logo: {
                x: 978,
                y: 978,
                width: 102,
                height: 102,
                horizontalAlignment: 'right',
            },
            website: {
                x: 1080,
                y: 0,
                horizontalAlignment: 'right',
                lineDistribution: 'down',
                includeBackgroundFill: true,
            },
            programInfo: {
                x: 489,
                y: 1019,
                horizontalAlignment: 'center',
                lineDistribution: 'center',
            },
            defaultPictureWebsiteDisabled: true,
            defaultPictureWebsiteExtraText: {
                fontSize: 30,
                text: {
                    "english": "#iamasurvivorcampaign",
                    "spanish": "#iamasurvivorcampaign",
                },
            },
        },
        {
            name: "8.5x11",
            label: "8.5x11",
            width: 1545,
            height: 2000,
            header: {
                x: 0,
                y: 231,
                width: 1545,
                height: 1769,
                horizontalAlignment: 'center',
                verticalAlignment: 'top',
            },
            defaultPicture: {
                x: 0,
                y: 490,
                width: 1545,
                height: 1322,
                horizontalAlignment: 'center',
                verticalAlignment: 'bottom',
            },
            antiDefaultPicture: {
                x: 0,
                y: 372,
                width: 1545,
                height: 1628,
                horizontalAlignment: 'center',
                verticalAlignment: 'top',
            },
            picture: {
                x: 0,
                y: 700,
                width: 1545,
                height: 1112,
                horizontalAlignment: 'center',
                verticalAlignment: 'bottom',
            },
            logo: {
                x: 1357,
                y: 1812,
                width: 188,
                height: 188,
                horizontalAlignment: 'right',
            },
            website: {
                x: 1545,
                y: 0,
                horizontalAlignment: 'right',
                lineDistribution: 'down',
                includeBackgroundFill: true,
            },
            programInfo: {
                x: 678,
                y: 1896,
                horizontalAlignment: 'center',
                lineDistribution: 'center',
            },
            defaultPictureWebsiteExtraText: {
                fontSize: 40,
                text: {
                    "english": "Campaign by Recognize Violence, Change Culture (RVCC)",
                    "spanish": "Campaña de Recognize Violence, Change Culture (RVCC)",
                },
            },
        },
        {
            name: "11x17",
            label: "11x17",
            width: 1294,
            height: 2000,
            header: {
                x: 0,
                y: 223,
                width: 1294,
                height: 1777,
                horizontalAlignment: 'center',
                verticalAlignment: 'top',
            },
            defaultPicture: {
                x: 0,
                y: 438,
                width: 1294,
                height: 1375,
                horizontalAlignment: 'center',
                verticalAlignment: 'bottom',
            },
            antiDefaultPicture: {
                x: 0,
                y: 364,
                width: 1294,
                height: 1636,
                horizontalAlignment: 'center',
                verticalAlignment: 'top',
            },
            picture: {
                x: 0,
                y: 692,
                width: 1294,
                height: 1121,
                horizontalAlignment: 'center',
                verticalAlignment: 'bottom',
            },
            logo: {
                x: 1107,
                y: 1813,
                width: 187,
                height: 187,
                horizontalAlignment: 'right',
            },
            website: {
                x: 1294,
                y: 0,
                horizontalAlignment: 'right',
                lineDistribution: 'down',
                includeBackgroundFill: true,
            },
            programInfo: {
                x: 553,
                y: 1896,
                horizontalAlignment: 'center',
                lineDistribution: 'center',
            },
            defaultPictureWebsiteExtraText: {
                fontSize: 40,
                text: {
                    "english": "Campaign by Recognize Violence, Change Culture (RVCC)",
                    "spanish": "Campaña de Recognize Violence, Change Culture (RVCC)",
                },
            },
        },
        {
            name: "12x18",
            label: "12x18",
            width: 1333,
            height: 2000,
            header: {
                x: 0,
                y: 240,
                width: 1333,
                height: 1760,
                horizontalAlignment: 'center',
                verticalAlignment: 'top',
            },
            defaultPicture: {
                x: 0,
                y: 438,
                width: 1333,
                height: 1400,
                horizontalAlignment: 'center',
                verticalAlignment: 'bottom',
            },
            antiDefaultPicture: {
                x: 0,
                y: 381,
                width: 1333,
                height: 1619,
                horizontalAlignment: 'center',
                verticalAlignment: 'top',
            },
            picture: {
                x: 0,
                y: 709,
                width: 1333,
                height: 1129,
                horizontalAlignment: 'center',
                verticalAlignment: 'bottom',
            },
            logo: {
                x: 1171,
                y: 1838,
                width: 162,
                height: 162,
                horizontalAlignment: 'right',
            },
            website: {
                x: 1333,
                y: 0,
                horizontalAlignment: 'right',
                lineDistribution: 'down',
                includeBackgroundFill: true,
            },
            programInfo: {
                x: 585,
                y: 1909,
                horizontalAlignment: 'center',
                lineDistribution: 'center',
            },
            defaultPictureWebsiteExtraText: {
                fontSize: 40,
                text: {
                    "english": "Campaign by Recognize Violence, Change Culture (RVCC)",
                    "spanish": "Campaña de Recognize Violence, Change Culture (RVCC)",
                },
            },
        },
    ]
}
